### PR TITLE
Added net7. Fixed typos. Small refactorings.

### PR DESCRIPTION
**Pull request by bogdandynamic**
Added net7. Fixed typos in file naming and code. Changed empty array initializations.

### CODE REVIEW

**Comment by bogdandynamic** [comment]
> Adding .NET 7 as a target won't add any value beyond what .NET 6 already provides.

I agree with you. 

The pull request consists mainly on fixing typos, and a little bit of code readability improvements. I read through the source code because I intend to present Grace to my team and implement it in some projects we're working on at the moment as a replacement to Microsoft's DI container.

If the pull request does not add any value to the project, feel free to reject it.

**Comment by ipjohnson** [comment]
Thank you for the PR, I'm going to take a little time to digest it but I'll merge it in the coming days.

**Comment by bogdandynamic** [comment]
@ipjohnson, thank you writing such a great functionality.

**Comment by ipjohnson** [comment]
Thank you for the kind words. This lgtm, I'll merge on saturday and put out a new RC package.

**Pull request merged**
